PImage tc1a,tc1b,tc2a,tc2b,tc3a,tc3b,tc4a,tc4b;

PImage[] militiaL,militiaR;
PImage[] menL,menR;
PImage[] swordL,swordR;
PImage[] champL,champR;
PImage[] archerL,archerR;
PImage[] crossR,crossL;
PImage[] arbL,arbR;
PImage[] longL,longR;
PImage[] spearL,spearR;
PImage[] pikeL,pikeR;
PImage[] halbL,halbR;
PImage[] scoutL,scoutR;
PImage[] lightL,lightR;
PImage[] knightL,knightR;
PImage[] paladinL,paladinR;
PImage[] elephantL,elephantR;

PImage[] militiaAL,militiaAR;
PImage[] menAL,menAR;
PImage[] swordAL,swordAR;
PImage[] champAL,champAR;
PImage[] archerAL,archerAR;
PImage[] crossAR,crossAL;
PImage[] arbAL,arbAR;
PImage[] longAL,longAR;
PImage[] spearAL,spearAR;
PImage[] pikeAL,pikeAR;
PImage[] halbAL,halbAR;
PImage[] scoutAL,scoutAR;
PImage[] lightAL,lightAR;
PImage[] knightAL,knightAR;
PImage[] paladinAL,paladinAR;
PImage[] elephantAL,elephantAR;

PImage[] militiaDL,militiaDR;
PImage[] menDL,menDR;
PImage[] swordDL,swordDR;
PImage[] champDL,champDR;
PImage[] archerDL,archerDR;
PImage[] crossDR,crossDL;
PImage[] arbDL,arbDR;
PImage[] longDL,longDR;
PImage[] spearDL,spearDR;
PImage[] pikeDL,pikeDR;
PImage[] halbDL,halbDR;
PImage[] scoutDL,scoutDR;
PImage[] lightDL,lightDR;
PImage[] knightDL,knightDR;
PImage[] paladinDL,paladinDR;
PImage[] elephantDL,elephantDR;

PImage militiaSL,militiaSR;
PImage menSL,menSR;
PImage swordSL,swordSR;
PImage champSL,champSR;
PImage archerSL,archerSR;
PImage crossSL,crossSR;
PImage arbSL,arbSR;
PImage longSL,longSR;
PImage scoutSL,scoutSR;
PImage lightSL,lightSR;
PImage knightSL,knightSR;
PImage paladinSL,paladinSR;
PImage spearSL,spearSR;
PImage pikeSL,pikeSR;
PImage halbSL,halbSR;
PImage elephantSL,elephantSR;
 

void loadImages() {
  tc1a = loadImage("Data/tc1a.jpg"); 
  tc1b = loadImage("Data/tc1b.jpg");
  tc2a = loadImage("Data/tc2a.gif"); 
  tc2b = loadImage("Data/tc2b.gif");
  tc4a = loadImage("Data/tc4a.gif"); 
  tc4b = loadImage("Data/tc4b.gif");
  
  militiaAL = Load(10,"miAL");
  militiaAR = Load(10,"miAR");
  menAL = Load(11,"meAL");
  menAR = Load(11,"meAR");
  swordAL = Load(9,"swAL");
  swordAR = Load(9,"swAR");
  champAL = Load(10,"chAL");
  champAR = Load(10,"chAR");
  archerAL = Load(10,"arAL");
  archerAR = Load(10,"arAR");
  crossAL = Load(10,"crAL");
  crossAR = Load(10,"crAR");
  arbAL = Load(11,"abAL");
  arbAR = Load(11,"abAR");
  longAL = Load(15,"loAL");
  longAR = Load(15,"loAR");
  spearAL = Load(10,"spAL");
  spearAR = Load(10,"spAR");
  pikeAL = Load(10,"pkAL");
  pikeAR = Load(10,"pkAR");
  halbAL = Load(10,"hlAL");
  halbAR = Load(10,"hlAR");
  scoutAL = Load(10,"scAL");
  scoutAR = Load(10,"scAR");
  lightAL = Load(10,"liAL");
  lightAR = Load(10,"liAR");
  knightAL = Load(10,"knAL");
  knightAR = Load(10,"knAR");
  paladinAL = Load(10,"plAL");
  paladinAR = Load(10,"plAR");
  elephantAL = Load(7,"elAL");
  elephantAR = Load(7,"elAR");
  
  militiaDR = Load(10,"miDR");
  militiaDL = Load(10,"miDL");
  menDL = Load(11,"meDL");
  menDR = Load(11,"meDR");
  swordDL = Load(10,"swDL");
  swordDR = Load(10,"swDR");
  champDL = Load(10,"chDL");
  champDR = Load(10,"chDR");
  archerDL = Load(10,"arDL");
  archerDR = Load(10,"arDR");
  crossDL = Load(10,"crDL");
  crossDR = Load(10,"crDR");
  arbDL = Load(10,"abDL");
  arbDR = Load(10,"abDR");
  longDL = Load(15,"loDL");
  longDR = Load(15,"loDR");
  spearDL = Load(10,"spDL");
  spearDR = Load(10,"spDR");
  pikeDL = Load(10,"pkDL");
  pikeDR = Load(10,"pkDR");
  halbDL = Load(10,"hlDL");
  halbDR = Load(10,"hlDR");
  scoutDL = Load(8,"scDL");
  scoutDR = Load(8,"scDR");
  lightDL = Load(10,"liDL");
  lightDR = Load(10,"liDR");
  knightDL = Load(10,"knDL");
  knightDR = Load(10,"knDR");
  paladinDL = Load(10,"plDL");
  paladinDR = Load(10,"plDR");
  elephantDL = Load(15,"elDL");
  elephantDR = Load(15,"elDR");
  
  militiaR = Load(12,"miR");
  militiaL = Load(12,"miL");
  menL = Load(11,"meL");
  menR = Load(11,"meR");
  swordL = Load(10,"swL");
  swordR = Load(10,"swR");
  champL = Load(10,"chL");
  champR = Load(10,"chR");
  archerL = Load(9,"arL");
  archerR = Load(9,"arR");
  crossL = Load(12,"crL");
  crossR = Load(12,"crR");
  arbL = Load(10,"abL");
  arbR = Load(10,"abR");
  longL = Load(12,"loL");
  longR = Load(12,"loR");
  spearL = Load(10,"spL");
  spearR = Load(10,"spR");
  pikeL = Load(10,"pkL");
  pikeR = Load(10,"pkR");
  halbL = Load(12,"hlL");
  halbR = Load(12,"hlR");
  scoutL = Load(10,"scL");
  scoutR = Load(10,"scR");
  lightL = Load(10,"liL");
  lightR = Load(10,"liR");
  knightL = Load(10,"knL");
  knightR = Load(10,"knR");
  paladinL = Load(10,"plL");
  paladinR = Load(10,"plR");
  elephantL = Load(10,"elL");
  elephantR = Load(10,"elR");
  
  //militiaSR = militiaR[4];
  //militiaSL = militiaL[4];
  //menSL = menL[9];
  //menSR = menR[9];
  //swordSL = swordL[4];
  //swordSR = swordR[4];
  //champSL = champL[9];
  //champSR = champR[9];
  //archerSL = archerL[2];
  //archerSR = archerR[2];
  //crossSL = crossL[11];
  //crossSR = crossR[11];
  //arbSL = arbL[9];
  //arbSR = arbR[9];
  //longSL = longL[4];
  //longSR = longR[4];
  //spearSL = spearL[9];
  //spearSR = spearR[9];
  //pikeSL = pikeL[7];
  //pikeSR = pikeR[7];
  //halbSL = halbL[9];
  //halbSR = halbR[9];
  //scoutSL = scoutL[1];
  //scoutSR = scoutR[1];
  //lightSL = lightL[9];
  //lightSR = lightR[9];
  //knightSL = knightL[9];
  //knightSR = knightR[9];
  //paladinSL =paladinL[9];
  //paladinSR =paladinR[9];
  //elephantSL = elephantL[7];
  //elephantSR = elephantR[7];
}

PImage[] Load(int len,String c) {
  PImage[] img = new PImage[len];
  for(int i=0;i<img.length;i++)  {
    img[i] = loadImage("Data/Animations/"+c+(i+1)+".gif");
  }
  return img;
}
